name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.IKEMEN_TOKEN }}"
          MERGE_LABELS: ".automerge,!.wip"
          MERGE_REMOVE_LABELS: ""
          MERGE_METHOD: "merge"
          MERGE_METHOD_LABELS: ".automerge=merge,.autosquash=squash,.autorebase=rebase"
          MERGE_METHOD_LABEL_REQUIRED: "false"
          MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
          MERGE_COMMIT_MESSAGE_REGEX: ""
          MERGE_FILTER_AUTHOR: ""
          MERGE_FORKS: "true"
          MERGE_RETRIES: "3"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_REQUIRED_APPROVALS: "0"
          MERGE_DELETE_BRANCH: "false"
          MERGE_DELETE_BRANCH_FILTER: ""
          MERGE_ERROR_FAIL: "true"
          MERGE_READY_STATE: "clean,has_hooks,unknown,unstable"
          UPDATE_LABELS: ".automerge,.autosquash,.autorebase"
          UPDATE_METHOD: "merge"
          UPDATE_RETRIES: "3"
          UPDATE_RETRY_SLEEP: "10000"
          PULL_REQUEST: ""
          BASE_BRANCHES: ""
