on:
  release:
    types:
      - created

permissions: write-all

name: changelog
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2
        with:
          token: ${{ secrets.IKEMEN_TOKEN }} 
