name: changelog

on:
  #push:
  #  tags:
  #    - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the new release'     
        required: true
        default: 'v0.0.0'

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get previous tag
        id: previousTag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true

      - name: Bump version and push tag
        id: latestTag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          default_prerelease_bump: false
          custom_tag: ${{ github.event.inputs.tag }}
          create_annotated_tag: false
          tag_prefix: ""
          # <keyword>:<release_type>:<changelog_section>
          custom_release_rules: >
            build:patch,
            chore:patch,
            docs:patch,
            feat:patch:New Features,
            fix:patch:Bug Fixes,
            other:patch,
            perf:patch,
            refactor:patch,
            style:patch,
            test:patch

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ steps.latestTag.outputs.new_tag }}
          toTag: ${{ steps.previousTag.outputs.tag }}
          # tag: ${{ github.ref_name }}
          writeToFile: false
          excludeTypes: build,chore,docs,other,perf,refactor,style,test
          includeInvalidCommits: false

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          allowUpdates: true
          draft: false
          tag: ${{ steps.latestTag.outputs.new_tag }}
          name: ${{ steps.latestTag.outputs.new_tag }}
          body: |
            ${{ steps.changelog.outputs.changes }}
            -----------------
            ${{ steps.latestTag.outputs.changelog }}

      #- name: Commit CHANGELOG.md
      #  uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
      #    branch: main
      #    commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
      #    file_pattern: CHANGELOG.md