name: changelog

on:
  #push:
  #  tags:
  #    - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the new release'     
        required: true
        default: 'v0.0.0'

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get latest tag
        id: toTag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true

      - name: Commit new tag
        uses: tvdias/github-tagger@v0.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ github.event.inputs.tag }}"

      - name: Get latest tag
        id: fromTag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true

      - name: Print tags
        run: |
          echo "toTag: ${{ steps.toTag.outputs.tag }}"
          echo "fromTag: ${{ steps.fromTag.outputs }}"
        shell: bash

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ steps.fromTag.outputs }}
          toTag: ${{ steps.toTag.outputs.tag }}
          # tag: ${{ github.ref_name }}
          writeToFile: false
          excludeTypes: build,chore,docs,other,perf,refactor,style,test
          includeInvalidCommits: false

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ github.token }}
          allowUpdates: true
          draft: false
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}

      #- name: Commit CHANGELOG.md
      #  uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
      #    branch: main
      #    commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
      #    file_pattern: CHANGELOG.md