name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        cfg:
          - { os: 'windows-2022', goos: 'windows', goarch: 'amd64', bin: 'Ikemen_GO.exe', cc: x86_64-w64-mingw32-gcc, ccx: x86_64-w64-mingw32-g++ }
          - { os: 'ubuntu-22.04', goos: 'linux',   goarch: 'amd64', bin: 'Ikemen_GO_Linux' }
          - { os: 'macos-11',     goos: 'darwin',  goarch: 'amd64', bin: 'Ikemen_GO_MacOS' }
          
    runs-on: ${{ matrix.cfg.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup Golang with cache
      uses: magnetikonline/action-golang-cache@v3
      with:
        go-version: 1.20.1
        #go-version-file: go.mod
        #cache-key-suffix: -ikemen

    - name: Setup dependencies caches (windows)
      if: runner.os == 'windows'
      uses: actions/cache@v3
      with:
        path: |
          C:\ProgramData\chocolatey\lib\git*
          C:\ProgramData\chocolatey\lib\zip*
        key: ${{ runner.os }}-dependencies-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-

    - name: Install dependencies
      run: |
        echo "Installing dependencies"
        if [[ "$OSTYPE" == "windows"* ]]; then
          choco install zip git
        elif [[ "$OSTYPE" == "darwin"* ]]; then
          brew install zip git libx11 libxcursor xrandr libxinerama libxi gtk+3 mesa
        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
          sudo apt-get update -y
          sudo apt-get install -y zip git libx11-dev libxcursor-dev x11-xserver-utils libxrandr-dev libxinerama-dev libxi-dev libasound2-dev libgtk-3-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-dev libxxf86vm-dev
        fi

    - name: Build
      run: |
        go env -w GO111MODULE=on
        go mod download
        if [ "$RUNNER_OS" == "Windows" ]; then
          go build -v -ldflags "-H windowsgui" -o ./$binName ./src
        else
          go build -v -o ./$binName ./src
        fi
      shell: bash
      env:
        CGO_ENABLED: 1
        GOOS: ${{ matrix.cfg.goos }}
        GOARCH: ${{ matrix.cfg.goarch }}
        binName: ${{ matrix.cfg.bin }}
        #CC: ${{ matrix.cfg.cc }}
        #CCX: ${{ matrix.cfg.cxx }}
