# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        sudo apt update -y
        sudo apt install -y git libx11-dev libxcursor-dev x11-xserver-utils libxrandr-dev libxinerama-dev libxi-dev libasound2-dev libgtk-3-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-dev libxxf86vm-dev
        export PATH=$PATH:/usr/local/go/bin
        export GOPATH=./go
        export GOPATH=/root/test-cicd/go
        export CGO_ENABLED=1
        sudo go mod download
        sudo go build -o ./Ikemen_GO.exe ./src
        

    - name: Deploy
      run: |
        sudo apt update -y
        sudo apt install -y git libx11-dev libxcursor-dev x11-xserver-utils libxrandr-dev libxinerama-dev libxi-dev libasound2-dev libgtk-3-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-dev libxxf86vm-dev
        export PATH=$PATH:/usr/local/go/bin
        export GOPATH=./go
        export GOPATH=/root/test-cicd/go
        export CGO_ENABLED=1
        sudo go mod download
        sudo go build -o ./Ikemen_GO.exe ./src
        
        git clone https://github.com/ikemen-engine/Ikemen_GO-Elecbyte-Screenpack.git
        mkdir deploy
        cp -rfp data external ./deploy
        cp -rfp Ikemen_GO-Elecbyte-Screenpack/chars Ikemen_GO-Elecbyte-Screenpack/data Ikemen_GO-Elecbyte-Screenpack/font Ikemen_GO-Elecbyte-Screenpack/stages ./deploy
        cp -fp Ikemen_GO-Elecbyte-Screenpack/LICENCE.txt ./deploy/ScreenpackLicense.txt
        
        
