name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y mkdir git libx11-dev libxcursor-dev x11-xserver-utils libxrandr-dev libxinerama-dev libxi-dev libasound2-dev libgtk-3-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-dev libxxf86vm-dev

    - name: Build
      env:
        #PATH: ${{ env.PATH }}:/usr/local/go/bin
        GOPATH: ${{ github.workspace }}/go
        CGO_ENABLED: 1
      run: |
        PATH=$PATH:/usr/local/go/bin
        cd ${{ github.workspace }}
        mkdir ${{ env.GOPATH }}
        sudo chown -R $USER:$USER ${{ env.GOPATH }}
        go mod download
        go build -o ./Ikemen_GO ./src

    - name: Deploy
      env:
        #PATH: ${{ env.PATH }}:/usr/local/go/bin
        GOPATH: ${{ github.workspace }}/go
        CGO_ENABLED: 1
      run: |
        PATH=$PATH:/usr/local/go/bin
        cd ${{ github.workspace }}
        # Prepare repo assets
        mkdir deploy
        # Prepare repo assets
        cp -rfp data external ./deploy
        cp -f ./Ikemen_GO ./deploy
        # Prepare screenpack assets
        git clone https://github.com/ikemen-engine/Ikemen_GO-Elecbyte-Screenpack.git
        cd ./Ikemen_GO-Elecbyte-Screenpack
        cp -rfp chars data font stages ./../deploy
        cp -fp LICENCE.txt ./../deploy/ScreenpackLicense.txt
        cd ${{ github.workspace }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./deploy/*
        tag_name: v1.0.0
        body: |
          Release version 1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.IKEMEN_TOKEN }}
  
