name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Golang with cache (windows)
      uses: magnetikonline/action-golang-cache@v3
      with:
        go-version: 1.20.1
        #go-version-file: go.mod
        #cache-key-suffix: -ikemen

    - name: Setup dependencies caches (windows)
      uses: actions/cache@v3
      with:
        path: |
          C:\ProgramData\chocolatey\lib\git*
          C:\ProgramData\chocolatey\lib\zip*
        key: ${{ runner.os }}-dependencies-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-

    - name: Install dependencies (windows)
      run: |
        echo "Installing dependencies (windows)"
        choco install zip git

    - name: Build (windows)
      run: |
        echo "Building (windows)"
        set CGO_ENABLED=1
        set CC=x86_64-w64-mingw32-gcc
        set CXX=x86_64-w64-mingw32-g++
        set GOOS=windows
        set GOARCH=amd64
        go env -w GO111MODULE=on
        go mod download
        go build -o ./Ikemen_GO.exe ./src

    - name: Deploy (windows)
      run: |
        echo "Deploying (windows)"
        mkdir deploy
        cp Ikemen_GO.exe deploy\
        echo "Preparing repo assets (windows)"
        xcopy /E /I data\* deploy\data\
        xcopy /E /I external\* deploy\external\
        echo "Preparing screenpack assets (windows)"
        git clone https://github.com/ikemen-engine/Ikemen_GO-Elecbyte-Screenpack.git
        xcopy /E /I Ikemen_GO-Elecbyte-Screenpack\chars\* deploy\chars\
        xcopy /E /I Ikemen_GO-Elecbyte-Screenpack\data\* deploy\data\
        xcopy /E /I Ikemen_GO-Elecbyte-Screenpack\font\* deploy\font\
        xcopy /E /I Ikemen_GO-Elecbyte-Screenpack\stages\* deploy\stages\
        cp Ikemen_GO-Elecbyte-Screenpack\LICENCE.txt deploy\ScreenpackLicense.txt
        echo "Zipping deploy directory (windows)"
        cd deploy
        zip -r ../Ikemen_GO-v1.0.7-windows.zip *
        echo "Successfully prepared assets for deployment (windows)"

    - name: Create Release (windows)
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./Ikemen_GO-v1.0.7-windows.zip
        tag_name: v1.0.7-windows
        body: |
          Release version 1.0.7-windows
      env:
        GITHUB_TOKEN: ${{ secrets.IKEMEN_TOKEN }}

        
