# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y git libx11-dev libxcursor-dev x11-xserver-utils libxrandr-dev libxinerama-dev libxi-dev libasound2-dev libgtk-3-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-dev libxxf86vm-dev

    - name: Build
      run: |
        export PATH=$PATH:/usr/local/go/bin
        export GOPATH=/root/test-cicd/go
        export CGO_ENABLED=1
        sudo go mod download
        sudo go build -o ./Ikemen_GO.exe ./src

    - name: Deploy
      run: |
        export PATH=$PATH:/usr/local/go/bin
        export GOPATH=./go
        export CGO_ENABLED=1
        sudo go mod download
        sudo go build -o ./Ikemen_GO.exe ./src

        sudo git clone https://github.com/ikemen-engine/Ikemen_GO-Elecbyte-Screenpack.git
        sudo mkdir deploy
        sudo cp -rfp data external ./deploy
        sudo cp -rfp Ikemen_GO-Elecbyte-Screenpack/chars Ikemen_GO-Elecbyte-Screenpack/data Ikemen_GO-Elecbyte-Screenpack/font Ikemen_GO-Elecbyte-Screenpack/stages ./deploy
        sudo cp -fp Ikemen_GO-Elecbyte-Screenpack/LICENCE.txt ./deploy/ScreenpackLicense.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./deploy/*
        tag_name: v1.0.0
        body: |
          Release version 1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.IKEMEN_TOKEN }}

