name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  cicd:
    runs-on: ubuntu-latest
    env:
      PATH: ${{ env.PATH }}:/usr/local/go/bin
      GOPATH: /root/test-cicd/go
      CGO_ENABLED: 1
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y git libx11-dev libxcursor-dev x11-xserver-utils libxrandr-dev libxinerama-dev libxi-dev libasound2-dev libgtk-3-dev libgl1-mesa-dev libglu1-mesa-dev libgtk-3-dev libxxf86vm-dev

    - name: Build
      run: |
        sudo go mod download
        sudo go build -o ./Ikemen_GO ./src

    - name: Deploy
      run: |
        mkdir deploy
        # Prepare repo assets
        cp -rfp data external ./deploy
        cp -f ./Ikemen_GO ./deploy
        # Prepare screenpack assets
        git clone https://github.com/ikemen-engine/Ikemen_GO-Elecbyte-Screenpack.git
        cd ./Ikemen_GO-Elecbyte-Screenpack
        cp -rfp chars data font stages ./../deploy
        cp -fp LICENCE.txt ./../deploy/ScreenpackLicense.txt
        cd $GITHUB_WORKSPACE

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./deploy/*
        tag_name: v1.0.0
        body: |
          Release version 1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.IKEMEN_TOKEN }}
