name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Install dependencies
      run: |
        echo "Installing dependencies"
        choco install mingw
        choco install zip

    - name: Build
      run: |
        echo "Building"
        export PATH=$PATH:/usr/local/go/bin
        export GOPATH=${{ github.workspace }}/go
        export CGO_ENABLED=1
        export CC=x86_64-w64-mingw32-gcc
        export CXX=x86_64-w64-mingw32-g++
        export GOOS=windows
        export GOARCH=amd64
        go env -w GO111MODULE=on
        go mod download
        go build -o ./Ikemen_GO.exe ./src

    - name: Deploy
      run: |
        echo "Deploying"
        mkdir ./deploy
        cp -rp data external ./deploy
        cp ./Ikemen_GO.exe ./deploy
        git clone https://github.com/ikemen-engine/Ikemen_GO-Elecbyte-Screenpack.git
        cd ./Ikemen_GO-Elecbyte-Screenpack
        cp -rp chars data font stages ${{ github.workspace }}/deploy
        cp -p LICENCE.txt ${{ github.workspace }}/ScreenpackLicense.txt
        echo "Succesfully prepared assets for deployment"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./deploy/*
        tag_name: v1.0.1
        body: |
          Release version 1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.IKEMEN_TOKEN }}

