name: lint

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, edited, reopened, synchronize]

jobs:
  lint-pr-title:
    name: PR title
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.7.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title-regex: "\\bbuild|ci|docs|feat|fix|perf|refactor|style|test\\b\\(?[^\\)]*\\)?: .+$"
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: false
          on-failed-regex-comment: |
            Don't worry, if you can't fix the problem with the PR title, a person who takes care of things will handle it.
            
            We use precise git commit title formatting for readable messages and to generate auto releases and change log:
            `<type>(<scope>): <description>`
            where `<type>` must be one of the following: 
            - build: Changes that affect the build system or external dependencies
            - ci: Changes to our CI configuration files and scripts
            - docs: Documentation only changes
            - feat: A new feature
            - fix: A bug fix
            - perf: A code change that improves performance
            - refactor: A code change that neither fixes a bug nor adds a feature
            - style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
            - test: Adding missing tests or correcting existing tests
            `(<scope>)` declaration is optional and can be omitted.
          on-succeeded-regex-dismiss-review-comment: |
            PR title matches our git commit title formatting guidelines. All good!
