name: Lint

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

permissions:
  checks: write
  contents: write

jobs:
  style-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version: ~1.20

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          gofmt: true
          continue_on_error: false
          auto_fix: true
          commit_message: "style: fix code style issues with ${linter}"
          neutral_check_on_warning: true